### ISSUE TITLE
elasticsearch 1.5.2  使用pinyin 分词

### ISSUE THREAD

**Issue by adonis2014** [medcl/elasticsearch-analysis-pinyin#12]
Caused by: org.elasticsearch.ElasticsearchIllegalArgumentException: failed to find analyzer type [null] or tokenizer for [pinyin_analyzer]
	at org.elasticsearch.index.analysis.AnalysisModule.configure(AnalysisModule.java:383)
	at org.elasticsearch.common.inject.AbstractModule.configure(AbstractModule.java:60)
	at org.elasticsearch.common.inject.spi.Elements$RecordingBinder.install(Elements.java:204)
	at org.elasticsearch.common.inject.spi.Elements.getElements(Elements.java:85)
	at org.elasticsearch.common.inject.InjectorShell$Builder.build(InjectorShell.java:130)
	at org.elasticsearch.common.inject.InjectorBuilder.build(InjectorBuilder.java:99)
	at org.elasticsearch.common.inject.InjectorImpl.createChildInjector(InjectorImpl.java:131)
	at org.elasticsearch.common.inject.ModulesBuilder.createChildInjector(ModulesBuilder.java:69)
	at org.elasticsearch.indices.IndicesService.createIndex(IndicesService.java:328)
	... 8 more
[2015-05-01 23:39:31,625][WARN ][cluster.action.shard     ] [Brynocki] [medcl][1] received shard failed for [medcl][1], node[aUJOyVgfTzmo3P-okd9M3A], [P], s[INITIALIZING], indexUUID [jRV45HekR4Og1tlDYEgs1Q], reason [shard failure [failed to create index][IndexCreationException[[medcl] failed to create index]; nested: ElasticsearchIllegalArgumentException[failed to find analyzer type [null] or tokenizer for [pinyin_analyzer]]; ]]

**Comment by adonis2014** [comment]
在es 1.3.4 上使用拼音分词 没有错误，1.5.2 出现以上错误。

**Comment by medcl** [comment]
es1.6.0的走起,或者你自己下载源码编译,修改下pom.xml里面的es版本就行了,,https://github.com/medcl/elasticsearch-rtf/tree/1.6.0
