### ISSUE TITLE
README CreateMapping 操作失败: failed to find analyzer type [null] or tokenizer for [pinyin_analyzer]

### ISSUE THREAD

**Issue by zhugw** [medcl/elasticsearch-analysis-pinyin#13]
elasticsearch版本是1.6.0 
git clone 工程 后, 执行mvn package,然后通过如下方式安装插件
plugin --install analysis-pinyin --url file:///#{path}/elasticsearch-analysis-pinyin/target/releases/elasticsearch-analysis-pinyin-1.3.0.zip

之后照着README上的步骤操作时, 在Creat Mapping时老是会报错:
{"error":"IndexCreationException[[medcl] failed to create index]; nested: ElasticsearchIllegalArgumentException[failed to find analyzer type [null] or tokenizer for [pinyin_analyzer]]; ","status":400}
服务器端的错误日志如下:
Caused by: org.elasticsearch.ElasticsearchIllegalArgumentException: failed to find analyzer type [null] or tokenizer for [pinyin_analyzer]
	at org.elasticsearch.index.analysis.AnalysisModule.configure(AnalysisModule.java:383)
	at org.elasticsearch.common.inject.AbstractModule.configure(AbstractModule.java:60)
	at org.elasticsearch.common.inject.spi.Elements$RecordingBinder.install(Elements.java:204)
	at org.elasticsearch.common.inject.spi.Elements.getElements(Elements.java:85)
	at org.elasticsearch.common.inject.InjectorShell$Builder.build(InjectorShell.java:130)
	at org.elasticsearch.common.inject.InjectorBuilder.build(InjectorBuilder.java:99)
	at org.elasticsearch.common.inject.InjectorImpl.createChildInjector(InjectorImpl.java:131)
	at org.elasticsearch.common.inject.ModulesBuilder.createChildInjector(ModulesBuilder.java:69)
	at org.elasticsearch.indices.IndicesService.createIndex(IndicesService.java:336)

请问我是遗漏了哪一个关键步骤吗?

**Comment by medcl** [comment]
配置文件有放吗？ rtf里面有1.6的分支，可以去看看

send via my Phone.

**Comment by zhugw** [comment]
我在elasticsearch.yml中做了如下的配置
$ tail elasticsearch.yml 
  analysis:
    analyzer:
      pinyin_analyzer:
        tokenizer: xq_pinyin
        filter: [standard,nGram]
    tokenizer:
      xq_pinyin:
        type: pinyin
        first_letter: "prefix"
        padding_char: ""           

如果我忽略之前的步骤,直接从3.Indexing开始的话, 似乎一切正常.
4.Have a try中只有前两个有hits,剩下的hits为空.这个结果是正常的吗?

**Comment by caoyujie** [comment]
我知道哪里错了， "tokenizer" : ["my_pinyin"],   把后边的中括号去掉就OK乐

**Comment by medcl** [comment]
ok

**Comment by dengshuan** [comment]
I followed the *README* instructions and got the same error and spent about half an hour to figure out the reasons. And finally find this closed issue, @caoyujie method solves the problem.

@medcl Since you closed this issue, why not update the *README* file. This would save a lot of time for beginners I bet.

**Comment by medcl** [comment]
Hi,@dengshuan you are right，thanks for your kindly suggestion, let me fix it.

**Comment by dengshuan** [comment]
:+1:
