### ISSUE TITLE
在Setting下建立analyzer时候的时候，filter字段中按顺序定义pinyin和synonym会报错

### ISSUE THREAD

**Issue by touichibon** [medcl/elasticsearch-analysis-pinyin#154]
# 代码段描述：词典格式检查过了没有问题，注释的部分如果执行，则不会有错误。求帮忙，谢谢。
.startObject("smart")
	.field("tokenizer", "ik_smart")
	//.array("filter", "my_synonym", "pinyin")
	.array("filter", "pinyin", "my_synonym")
.endObject()

.startObject("filter")
     .startObject("my_synonym")
		.field("type", "synonym")
		.field("synonyms_path", "analysis/synonym.txt")
    .endObject()
								
    .startObject("pinyin")
		.field("type", "pinyin")
		.field("keep_separate_first_letter", false)
	        .field("keep_full_pinyin", false)
		.field("keep_original", true)
		.field("limit_first_letter_length", "16")
		.field("lowercase", true)
		.field("remove_duplicated_term", true)
		.field("keep_joined_full_pinyin", true)								
    .endObject()
.endObject()

最后想实现在普通同义词扩展的基础上，输入拼音比如laoshi 也能同义词显示出老师和教师。

## 具体报错信息：
Exception in thread "main" java.lang.IllegalArgumentException: failed to build synonyms
	at org.elasticsearch.index.analysis.SynonymTokenFilterFactory$Factory.<init>(SynonymTokenFilterFactory.java:154)
	at org.elasticsearch.index.analysis.SynonymTokenFilterFactory.createPerAnalyzerSynonymFactory(SynonymTokenFilterFactory.java:110)
	at org.elasticsearch.index.analysis.CustomAnalyzerProvider.checkAndApplySynonymFilter(CustomAnalyzerProvider.java:119)
	at org.elasticsearch.index.analysis.CustomAnalyzerProvider.build(CustomAnalyzerProvider.java:85)
	at org.elasticsearch.index.analysis.AnalysisRegistry.processAnalyzerFactory(AnalysisRegistry.java:534)
	at org.elasticsearch.index.analysis.AnalysisRegistry.build(AnalysisRegistry.java:464)
	at org.elasticsearch.index.analysis.AnalysisRegistry.build(AnalysisRegistry.java:159)
	at org.elasticsearch.index.IndexService.<init>(IndexService.java:160)
	at org.elasticsearch.index.IndexModule.newIndexService(IndexModule.java:361)
	at org.elasticsearch.indices.IndicesService.createIndexService(IndicesService.java:448)
	at org.elasticsearch.indices.IndicesService.createIndex(IndicesService.java:404)
	at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService$IndexCreationTask.execute(MetaDataCreateIndexService.java:439)
	at org.elasticsearch.cluster.ClusterStateUpdateTask.execute(ClusterStateUpdateTask.java:45)
	at org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:640)
	at org.elasticsearch.cluster.service.MasterService.calculateTaskOutputs(MasterService.java:270)
	at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:195)
	at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:130)
	at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:150)
	at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:188)
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:568)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:247)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:210)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: NotSerializableExceptionWrapper[parse_exception: Invalid synonym rule at line 1]; nested: IllegalArgumentException[term: 人选 analyzed to a token (renxuan) with position increment != 1 (got: 0)];
	at org.apache.lucene.analysis.synonym.SolrSynonymParser.parse(SolrSynonymParser.java:72)
	at org.elasticsearch.index.analysis.SynonymTokenFilterFactory$Factory.<init>(SynonymTokenFilterFactory.java:150)
	... 24 more
Caused by: java.lang.IllegalArgumentException: term: 人选 analyzed to a token (renxuan) with position increment != 1 (got: 0)
	at org.apache.lucene.analysis.synonym.SynonymMap$Parser.analyze(SynonymMap.java:325)
	at org.apache.lucene.analysis.synonym.SolrSynonymParser.addInternal(SolrSynonymParser.java:114)
	at org.apache.lucene.analysis.synonym.SolrSynonymParser.parse(SolrSynonymParser.java:70)
	... 25 more

**Comment by kin122** [comment]
@touichibon  synonym filter 放在 pinyin filter 之前处理呢
