### ISSUE TITLE
请问大神，ik 和 pinyin 结合 报错原因是什么？

### ISSUE THREAD

**Issue by zfha** [medcl/elasticsearch-analysis-pinyin#188]
版本6.4.0

docker部署，plugins 和 data 都挂载在外面

setting

```
PUT test_index
{
  "index" : {
    "analysis" : {
      "analyzer" : {
        "ik_pinyin_analyzer" : {
          "type":"custom",
          "tokenizer" : "ik_smart",
          "filter" : ["my_pinyin","word_delimiter"]
        }
      },
      "filter" : {
        "my_pinyin" : {
          "type" : "pinyin",
          "first_letter" : "prefix",
          "padding_char" : " "
        }
      }
    }
  }
}
```
分词分析

```
POST test_index/_analyze
{
  "analyzer": "ik_pinyin_analyzer",
  "text":"1"
}
```

控制台报错：
```
{
  "error": {
    "root_cause": [
      {
        "type": "remote_transport_exception",
        "reason": "[pczuo-0][172.17.0.2:9300][indices:admin/analyze[s]]"
      }
    ],
    "type": "null_pointer_exception",
    "reason": null
  },
  "status": 500
}
```

elasticsearch报错
```
org.elasticsearch.transport.RemoteTransportException: [pczuo-0][172.17.0.2:9300][indices:admin/analyze[s]]
Caused by: java.lang.NullPointerException
	at org.wltea.analyzer.dic.Dictionary.isStopWord(Dictionary.java:386) ~[?:?]
	at org.wltea.analyzer.core.AnalyzeContext.getNextLexeme(AnalyzeContext.java:316) ~[?:?]
	at org.wltea.analyzer.core.IKSegmenter.next(IKSegmenter.java:95) ~[?:?]
	at org.wltea.analyzer.lucene.IKTokenizer.incrementToken(IKTokenizer.java:88) ~[?:?]
	at org.elasticsearch.index.analysis.PinyinTokenFilter.incrementToken(PinyinTokenFilter.java:81) ~[?:?]
	at org.apache.lucene.analysis.miscellaneous.WordDelimiterFilter.incrementToken(WordDelimiterFilter.java:250) ~[lucene-analyzers-common-7.4.0.jar:7.4.0 9060ac689c270b02143f375de0348b7f626adebc - jpountz - 2018-06-18 16:52:07]
	at org.elasticsearch.action.admin.indices.analyze.TransportAnalyzeAction.simpleAnalyze(TransportAnalyzeAction.java:267) ~[elasticsearch-6.4.0.jar:6.4.0]
	at org.elasticsearch.action.admin.indices.analyze.TransportAnalyzeAction.analyze(TransportAnalyzeAction.java:244) ~[elasticsearch-6.4.0.jar:6.4.0]
	at org.elasticsearch.action.admin.indices.analyze.TransportAnalyzeAction.shardOperation(TransportAnalyzeAction.java:165) ~[elasticsearch-6.4.0.jar:6.4.0]
	at org.elasticsearch.action.admin.indices.analyze.TransportAnalyzeAction.shardOperation(TransportAnalyzeAction.java:81) ~[elasticsearch-6.4.0.jar:6.4.0]
	at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$ShardTransportHandler.messageReceived(TransportSingleShardAction.java:287) ~[elasticsearch-6.4.0.jar:6.4.0]
	at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$ShardTransportHandler.messageReceived(TransportSingleShardAction.java:280) ~[elasticsearch-6.4.0.jar:6.4.0]
	at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:30) ~[elasticsearch-6.4.0.jar:6.4.0]
	at org.elasticsearch.xpack.security.transport.SecurityServerTransportInterceptor$ProfileSecuredRequestHandler$1.doRun(SecurityServerTransportInterceptor.java:251) [x-pack-security-6.4.0.jar:6.4.0]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-6.4.0.jar:6.4.0]
	at org.elasticsearch.xpack.security.transport.SecurityServerTransportInterceptor$ProfileSecuredRequestHandler.messageReceived(SecurityServerTransportInterceptor.java:309) [x-pack-security-6.4.0.jar:6.4.0]
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:66) [elasticsearch-6.4.0.jar:6.4.0]
	at org.elasticsearch.transport.TransportService$7.doRun(TransportService.java:665) [elasticsearch-6.4.0.jar:6.4.0]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:723) [elasticsearch-6.4.0.jar:6.4.0]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-6.4.0.jar:6.4.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:844) [?:?]
```

**Comment by JasonJunJun** [comment]
我也碰到了这个问题，我是通过持久化`/usr/share/elasticsearch/config/analysis-ik`解决的。如下所示：

```shell script
docker volume create Elasticsearch_data
docker volume create Elasticsearch_plugins
docker volume create Elasticsearch_config_analysis-ik

docker run -d --name Elasticsearch \
-p 9200:9200 -p 9300:9300 \
-e "cluster.name=guiderank-es" -e "discovery.type=single-node" \
-v Elasticsearch_data:/usr/share/elasticsearch/data \
-v Elasticsearch_plugins:/usr/share/elasticsearch/plugins \
-v Elasticsearch_config_analysis-ik:/usr/share/elasticsearch/config/analysis-ik \
elasticsearch:6.5.4

# install plugins
docker exec -it Elasticsearch bash
bin/elasticsearch-plugin install https://github.com/medcl/elasticsearch-analysis-ik/releases/download/v6.5.4/elasticsearch-analysis-ik-6.5.4.zip

docker restart Elasticsearch
```

**Comment by kin122** [comment]
@zfha 检查一下，目录是否挂对
