### ISSUE TITLE
elasticsearch7.3.2 elasticsearch-analysis-pinyin7.x-master兼容问题

### ISSUE THREAD

**Issue by keepkeeping** [medcl/elasticsearch-analysis-pinyin#232]
[2020-07-03T09:28:01,001][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [node-208] fatal error in thread [elasticsearch[node-208][clusterApplierService#updateTask][T#1]], exiting
java.lang.NoSuchMethodError: org.elasticsearch.index.analysis.AbstractTokenizerFactory.<init>(Lorg/elasticsearch/index/IndexSettings;Lorg/elasticsearch/common/settings/Settings;Ljava/lang/String;)V
	at org.elasticsearch.index.analysis.PinyinAbbreviationsTokenizerFactory.<init>(PinyinAbbreviationsTokenizerFactory.java:12) ~[?:?]
	at org.elasticsearch.index.analysis.AnalysisRegistry.buildMapping(AnalysisRegistry.java:447) ~[elasticsearch-7.3.2.jar:7.3.2]
	at org.elasticsearch.index.analysis.AnalysisRegistry.buildTokenizerFactories(AnalysisRegistry.java:288) ~[elasticsearch-7.3.2.jar:7.3.2]
	at org.elasticsearch.index.analysis.AnalysisRegistry.build(AnalysisRegistry.java:212) ~[elasticsearch-7.3.2.jar:7.3.2]
	at org.elasticsearch.index.IndexService.<init>(IndexService.java:180) ~[elasticsearch-7.3.2.jar:7.3.2]
	at org.elasticsearch.index.IndexModule.newIndexService(IndexModule.java:411) ~[elasticsearch-7.3.2.jar:7.3.2]
	at org.elasticsearch.indices.IndicesService.createIndexService(IndicesService.java:563) ~[elasticsearch-7.3.2.jar:7.3.2]
	at org.elasticsearch.indices.IndicesService.createIndex(IndicesService.java:512) ~[elasticsearch-7.3.2.jar:7.3.2]
	at org.elasticsearch.indices.IndicesService.createIndex(IndicesService.java:165) ~[elasticsearch-7.3.2.jar:7.3.2]
	at org.elasticsearch.indices.cluster.IndicesClusterStateService.createIndices(IndicesClusterStateService.java:503) ~[elasticsearch-7.3.2.jar:7.3.2]
	at org.elasticsearch.indices.cluster.IndicesClusterStateService.applyClusterState(IndicesClusterStateService.java:265) ~[elasticsearch-7.3.2.jar:7.3.2]
	at org.elasticsearch.cluster.service.ClusterApplierService.lambda$callClusterStateAppliers$5(ClusterApplierService.java:495) ~[elasticsearch-7.3.2.jar:7.3.2]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:1.8.0_251]
	at org.elasticsearch.cluster.service.ClusterApplierService.callClusterStateAppliers(ClusterApplierService.java:493) ~[elasticsearch-7.3.2.jar:7.3.2]
	at org.elasticsearch.cluster.service.ClusterApplierService.applyChanges(ClusterApplierService.java:464) ~[elasticsearch-7.3.2.jar:7.3.2]
	at org.elasticsearch.cluster.service.ClusterApplierService.runTask(ClusterApplierService.java:418) ~[elasticsearch-7.3.2.jar:7.3.2]
	at org.elasticsearch.cluster.service.ClusterApplierService$UpdateTask.run(ClusterApplierService.java:165) ~[elasticsearch-7.3.2.jar:7.3.2]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:688) ~[elasticsearch-7.3.2.jar:7.3.2]
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:252) ~[elasticsearch-7.3.2.jar:7.3.2]
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:215) ~[elasticsearch-7.3.2.jar:7.3.2]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_251]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_251]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_251]

**Comment by keepkeeping** [comment]
plugin-descriptor.properties中我已经修改为elasticsearch.version=7.3.2，也还是不行

**Comment by keepkeeping** [comment]
最新分支的pom.xml中的 <elasticsearch.version>7.7.0</elasticsearch.version>改为 <elasticsearch.version>7.3.2</elasticsearch.version>，再把项目中报错的修改过来，重新打包就可以了
