### ISSUE TITLE
source为较长的纯数字时，导致cpu耗尽，严重影响写入性能

### ISSUE THREAD

**Issue by okailiang** [medcl/elasticsearch-analysis-pinyin#234]
当PinyinTokenizer.java中source为较长的纯数字时，如26677,28887,277029295,24464,23771,23488,26618,7,16815,20893,20310,26907,20616,165323040,17698,18550,9,22148,218415058,10194,18890,15645,18296,9183,8170,8034,8326,14469,185,4310,6888,5562,5057,4346,3170,2850,2707,842165,1094101,9843734,9843368,983055,1093008,983691,1092646,983320,1092279,98247,999546,981208,999180,981840,998815,981470,998452,980886,998085,980729,997180,989358,979990,996992,979620,996627,979248,996262,978877,995897,978510,995531,978140,995775,994797,977406,994430,976036,994063,976669,993698,976298,993926,992965,975556,992598,975187,992231,974816,991865,974446,991498,974075,991132,973705,990767,973334,990401,972965,989596,989668,972225,989302,971855,988935,971488,988570,971052,988206,970746,987840,970324 。

以下代码执行有误，Pinyin.pinyin()会导致pinyinList中所有元素均为为null。
`                List<String> pinyinList = Pinyin.pinyin(source);
                if (pinyinList.size() == 0) return false;
`

再向下执行，线程一直RUNNABLE，堆栈信息为：
`"elasticsearch[es-0][write][T#1]" #85 daemon prio=5 os_prio=0 tid=0x00007f5eac01f000 nid=0x242 runnable [0x00007f5e53835000]
   java.lang.Thread.State: RUNNABLE
	at org.elasticsearch.index.analysis.PinyinAlphabetTokenizer.parse(PinyinAlphabetTokenizer.java:63)
	at org.elasticsearch.index.analysis.PinyinAlphabetTokenizer.walk(PinyinAlphabetTokenizer.java:45)
	at org.elasticsearch.index.analysis.PinyinTokenFilter.parseBuff(PinyinTokenFilter.java:279)
	at org.elasticsearch.index.analysis.PinyinTokenFilter.readTerm(PinyinTokenFilter.java:161)
	at org.elasticsearch.index.analysis.PinyinTokenFilter.incrementToken(PinyinTokenFilter.java:86)
`

应该修改此处代码为
`  private boolean readTerm() {
    ... ...
            List<String> pinyinList = Pinyin.pinyin(source);
            if (isAllNull(pinyinList)) return false;
    .... ...
   }

    private boolean isAllNull(List<String> pinyinList) {
        for (String s : pinyinList) {
            if (StringUtil.isNotBlank(s)) {
                return false;
            }
        }
        return true;
    }
`

**Comment by KinYu668** [comment]
问题解决了吗？我这边也是遇到类似的问题，一个文档内容包含了<img src="">base64转码，会有一大堆字符串。占用Bulk线程，并且发现有部分task running状态持续了8个小时。

**Comment by okailiang** [comment]
通过上面的方法修改源码解决了，你试下

**Comment by kin122** [comment]
@okailiang 最好对这种复杂的数据做一个清洗
