### ISSUE TITLE
Elasticsearch7.12.0安装报错

### ISSUE THREAD

**Issue by huwentao1** [medcl/elasticsearch-analysis-pinyin#253]
有没有什么方法可以解决这个问题的
```python
[root@3f960650996e elasticsearch]# curl -XGET localhost:9200
{
  "name" : "3f960650996e",
  "cluster_name" : "docker-cluster",
  "cluster_uuid" : "-5YBH3-4REqp7Ff1tvekDA",
  "version" : {
    "number" : "7.12.0",
    "build_flavor" : "default",
    "build_type" : "docker",
    "build_hash" : "78722783c38caa25a70982b5b042074cde5d3b3a",
    "build_date" : "2021-03-18T06:17:15.410153305Z",
    "build_snapshot" : false,
    "lucene_version" : "8.8.0",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"
}
[root@3f960650996e elasticsearch]# bin/elasticsearch-plugin install https://github.com/medcl/elasticsearch-analysis-pinyin/archive/refs/tags/v7.12.0.zip
-> Installing https://github.com/medcl/elasticsearch-analysis-pinyin/archive/refs/tags/v7.12.0.zip
-> Downloading https://github.com/medcl/elasticsearch-analysis-pinyin/archive/refs/tags/v7.12.0.zip
[=================================================] 100%?? 
-> Failed installing https://github.com/medcl/elasticsearch-analysis-pinyin/archive/refs/tags/v7.12.0.zip
-> Rolling back https://github.com/medcl/elasticsearch-analysis-pinyin/archive/refs/tags/v7.12.0.zip
-> Rolled back https://github.com/medcl/elasticsearch-analysis-pinyin/archive/refs/tags/v7.12.0.zip
Exception in thread "main" java.nio.file.NoSuchFileException: /usr/share/elasticsearch/plugins/.installing-17396847961745653623/plugin-descriptor.properties
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:218)
        at java.base/java.nio.file.Files.newByteChannel(Files.java:375)
        at java.base/java.nio.file.Files.newByteChannel(Files.java:426)
        at java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:420)
        at java.base/java.nio.file.Files.newInputStream(Files.java:160)
        at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:173)
        at org.elasticsearch.plugins.InstallPluginCommand.loadPluginInfo(InstallPluginCommand.java:786)
        at org.elasticsearch.plugins.InstallPluginCommand.installPlugin(InstallPluginCommand.java:845)
        at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:245)
        at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:215)
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:75)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:116)
        at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:80)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:116)
        at org.elasticsearch.cli.Command.main(Command.java:79)
        at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:36)
[root@3f960650996e elasticsearch]# 

```

**Comment by itbsl** [comment]
我也遇到同样的问题，求解。

**Comment by phoenixgao** [comment]
tags里的zip包是源码，v7.12.0的release里没带编译好的的文件 @medcl

**Comment by medcl** [comment]
已修复
