### ISSUE TITLE
es2.1.1 下，pinyin,ik 共存插件导致 es 启动失败

### ISSUE THREAD

**Issue by yandy** [medcl/elasticsearch-analysis-pinyin#28]
只有 ik 或者只有 pinyin，es2.1.1 都能正常启动，但是一旦两个都安装，es 就会启动失败
```
[2015-12-30 03:07:04,397][INFO ][node                     ] [Eleggua] version[2.1.1], pid[1], build[40e2c53/2015-12-15T13:05:55Z]
[2015-12-30 03:07:04,399][INFO ][node                     ] [Eleggua] initializing ...
Exception in thread "main" java.lang.IllegalStateException: failed to load bundle [file:/usr/share/elasticsearch/plugins/pinyin/elasticsearch-analysis-pinyin-1.5.2.jar, file:/usr/share/elasticsearch/plugins/pinyin/pinyin4j-2.5.0.jar, file:/usr/share/elasticsearch/plugins/ik/commons-logging-1.2.jar, file:/usr/share/elasticsearch/plugins/ik/httpclient-4.4.1.jar, file:/usr/share/elasticsearch/plugins/ik/httpcore-4.4.1.jar, file:/usr/share/elasticsearch/plugins/ik/elasticsearch-analysis-ik-1.6.2.jar, file:/usr/share/elasticsearch/plugins/ik/commons-codec-1.9.jar] due to jar hell
Likely root cause: java.lang.IllegalStateException: jar hell!
class: org.elasticsearch.analysis.PinyinIndicesAnalysis$3
jar1: /usr/share/elasticsearch/plugins/pinyin/elasticsearch-analysis-pinyin-1.5.2.jar
jar2: /usr/share/elasticsearch/plugins/ik/elasticsearch-analysis-ik-1.6.2.jar
        at org.elasticsearch.bootstrap.JarHell.checkClass(JarHell.java:280)
        at org.elasticsearch.bootstrap.JarHell.checkJarHell(JarHell.java:186)
        at org.elasticsearch.plugins.PluginsService.loadBundles(PluginsService.java:336)
        at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:109)
        at org.elasticsearch.node.Node.<init>(Node.java:146)
        at org.elasticsearch.node.Node.<init>(Node.java:128)
        at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:145)
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:178))
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:285)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)
Refer to the log for complete error details.
```

**Comment by singit** [comment]
是的，要改下配置，插件名

**Comment by zcgewu** [comment]
@singit  你说的插件名是指plugin-descriptor.properties文件name吗？
