### ISSUE TITLE
Analyzer [pinyin_analyzer] must have a type associated 

### ISSUE THREAD

**Issue by zhangjiayin** [medcl/elasticsearch-analysis-pinyin#31]
Caused by: java.lang.IllegalArgumentException: Analyzer [pinyin_analyzer] must have a type associated with it
	at org.elasticsearch.index.analysis.AnalysisModule.configure(AnalysisModule.java:313)
	at org.elasticsearch.common.inject.AbstractModule.configure(AbstractModule.java:61)
	at org.elasticsearch.common.inject.spi.Elements$RecordingBinder.install(Elements.java:233)
	at org.elasticsearch.common.inject.spi.Elements.getElements(Elements.java:105)
	at org.elasticsearch.common.inject.InjectorShell$Builder.build(InjectorShell.java:143)
	at org.elasticsearch.common.inject.InjectorBuilder.build(InjectorBuilder.java:99)
	at org.elasticsearch.common.inject.InjectorImpl.createChildInjector(InjectorImpl.java:159)
	at org.elasticsearch.common.inject.ModulesBuilder.createChildInjector(ModulesBuilder.java:55)
	at org.elasticsearch.indices.IndicesService.createIndex(IndicesService.java:358)

**Comment by zhangjiayin** [comment]
I just follow this guide http://my.oschina.net/xiaohui249/blog/214505 use elasticseaerch2.1.1 and got the error above

**Comment by medcl** [comment]
@zhangjiayin 没有问题的，请问你是在哪一个步骤报错的？

**Comment by zhangjiayin** [comment]
可能是  "tokenizer" : ["my_pinyin"], 我修改成 "tokenizer" : "sr_pinyin"就好了。

**Comment by zhangjiayin** [comment]
另外我的结果 好像有些奇怪
curl 'http://xxxx:9200/xxxxxxx/_analyze?text=%e5%88%98%e5%be%b7%e5%8d%8e&analyzer=pinyin_analyzer&pretty'
{
  "tokens" : [ {
    "token" : "l",
    "start_offset" : 0,
    "end_offset" : 3,
    "type" : "word",
    "position" : 0
  }, {
    "token" : "li",
    "start_offset" : 0,
    "end_offset" : 3,
    "type" : "word",
    "position" : 0
  }, {
    "token" : "i",
    "start_offset" : 0,
    "end_offset" : 3,
    "type" : "word",
    "position" : 0
  }, {
    "token" : "iu",
    "start_offset" : 0,
    "end_offset" : 3,
    "type" : "word",
    "position" : 0
  }, {
    "token" : "u",
    "start_offset" : 0,
    "end_offset" : 3,
    "type" : "word",
    "position" : 0
  }, {
    "token" : "d",
    "start_offset" : 0,
    "end_offset" : 3,
    "type" : "word",
    "position" : 1
  }, {
    "token" : "de",
    "start_offset" : 0,
    "end_offset" : 3,
    "type" : "word",
    "position" : 1
  }, {
    "token" : "e",
    "start_offset" : 0,
    "end_offset" : 3,
    "type" : "word",
    "position" : 1
  }, {
    "token" : "h",
    "start_offset" : 0,
    "end_offset" : 3,
    "type" : "word",
    "position" : 2
  }, {
    "token" : "hu",
    "start_offset" : 0,
    "end_offset" : 3,
    "type" : "word",
    "position" : 2
  }, {
    "token" : "u",
    "start_offset" : 0,
    "end_offset" : 3,
    "type" : "word",
    "position" : 2
  }, {
    "token" : "ua",
    "start_offset" : 0,
    "end_offset" : 3,
    "type" : "word",
    "position" : 2
  }, {
    "token" : "a",
    "start_offset" : 0,
    "end_offset" : 3,
    "type" : "word",
    "position" : 2
  } ]
}

**Comment by medcl** [comment]
你用了 ngram filter吧

**Comment by zplzpl** [comment]
事实上，例子也加入了filter：NGram

**Comment by medcl** [comment]
太旧了，关闭了，有问题重新开
