### ISSUE TITLE
es-pinyin-1.7.2在es-v2.3.2下无法启动

### ISSUE THREAD

**Issue by occultskyrong** [medcl/elasticsearch-analysis-pinyin#42]
没找到安装的说明，只能去网上扒拉下，参照这个http://my.oschina.net/xiaohui249/blog/214505 编译了pinyin的jar包

生成两个jar包(`elasticsearch-analysis-pinyin-1.7.2.jar  pinyin4j-2.5.0.jar`)，已放在` [ES_HOME]/plugins/pinyin `路径下

然后`service elasticsearch start `
报下边的错误，感觉是版本的问题。

重装了es到2.3.2版本依然不行。。。。只能求教了。。。

```
正在启动 elasticsearch：Exception in thread "main" java.lang.IllegalStateException: Could not load plugin descriptor for existing plugin [pinyin]. Was the plugin built before 2.0?
Likely root cause: java.nio.file.NoSuchFileException: /usr/share/elasticsearch/plugins/pinyin/plugin-descriptor.properties
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
        at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
        at java.nio.file.Files.newByteChannel(Files.java:361)
        at java.nio.file.Files.newByteChannel(Files.java:407)
        at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384)
        at java.nio.file.Files.newInputStream(Files.java:152)
        at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:87)
        at org.elasticsearch.plugins.PluginsService.getPluginBundles(PluginsService.java:378)
        at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:128)
        at org.elasticsearch.node.Node.<init>(Node.java:158)
        at org.elasticsearch.node.Node.<init>(Node.java:140)
        at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:143)
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:178)
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:270)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)
Refer to the log for complete error details.
                                                           [失败]

```

**Comment by occultskyrong** [comment]
不知道是不是什么地方需要配置一下？？

**Comment by medcl** [comment]
不用直接打包，这里下载就好了
https://github.com/medcl/elasticsearch-analysis-pinyin/releases
解压放到es的plugins下面目录

**Comment by occultskyrong** [comment]
非常感谢，已解决~

不过建议你还是写个简单的安装说明吧。。。。

或者说我这种小白还是下意识的懒，都是直接ctrl+c了。。。。
