### ISSUE TITLE
how to install the plugin

### ISSUE THREAD

**Issue by wusi05** [medcl/elasticsearch-analysis-pinyin#62]
hello 
   i use your ik analyzer in my project, it works well. and when i use the elasticsearch-analysis-pinyin, i don't know how to install it, it is different from ik install ,so how can i use the elasticsearch-analysis-pinyin in my project. thanks a lot

**Comment by medcl** [comment]
install es plugin is easy, please go to this page: https://github.com/medcl/elasticsearch-analysis-pinyin/releases
according to your es's version, download corresponding zip file, unzip to your es' plugin's folder.
restart.

**Comment by wusi05** [comment]
thank for your answer,according to your method, elasticsearch start successfully,my ealstic version is 2.3.1, i download 1.7.1 analysis pinyin,when i put following code

PUT pinyin
{
  "index": {
    "analysis": {
      "analyzer": {
        "pinyin_analyzer": {
          "tokenizer": "my_pinyin"
        }
      },
      "tokenizer": {
        "my_pinyin": {
          "type": "pinyin",
          "keep_first_letter": true,
          "keep_full_pinyin": true,
          "keep_none_chinese": true,
          "keep_original": true,
          "limit_first_letter_length": 16,
          "lowercase": true,
          "trim_whitespace": true,
          "keep_none_chinese_in_first_letter": true
        }
      }
    }
  }
}

POST pinyin/folks/_mapping
{
  "properties": {
    "name": {
      "type": "keyword",
      "fields": {
        "pinyin": {
          "type": "text",
          "store": "no",
          "term_vector": "with_positions_offsets",
          "analyzer": "pinyin_analyzer",
          "boost": 10
        }
      }
    }
  }
}

**it show the error**

{
   "error": {
      "root_cause": [
         {
            "type": "mapper_parsing_exception",
            "reason": "No handler for type [keyword] declared on field [name]"
         }
      ],
      "type": "mapper_parsing_exception",
      "reason": "No handler for type [keyword] declared on field [name]"
   },
   "status": 400
}

so what should i do, Thank you

**Comment by medcl** [comment]
fileld data type `keyword` is for es v5.0 +, please  checkout this page in 2.x branch
https://github.com/medcl/elasticsearch-analysis-pinyin/tree/2.x

**Comment by wusi05** [comment]
it does work ,thanks a lot

**Comment by wusi05** [comment]
when i use pinyin-analyzer i find a question,  i insert into "美丽的花园" ,“花园”,"第一次看电影",when i match query "huayuan" , in return all include "第一次看电影"; and i add highlight area, but "美丽的花园" is covered by tags, code as following:

PUT askdog_v1
{
  "index": {
    "analysis": {
      "analyzer": {
        "pinyin_analyzer": {
          "tokenizer": "my_pinyin",
          "filter": [
            "word_delimiter",
            "nGram"
          ]
        }
      },
      "tokenizer": {
        "my_pinyin": {
          "type": "pinyin",
          "first_letter": "prefix",
          "padding_char": " "
        }
      }
    }
  }
}

PUT askdog_v1/experience/_mapping
{
  "experience": {
    "properties": {
      "name": {
        "type": "multi_field",
        "fields": {
          "name": {
            "type": "string",
            "store": "no",
            "term_vector": "with_positions_offsets",
            "analyzer": "pinyin_analyzer"
          },
          "primitive": {
            "type": "string",
            "store": "yes",
            "analyzer": "keyword"
          }
        }
      }
    }
  }
}

POST askdog_v1/experience/1
{
  "name":"美丽的花园"
}

POST askdog_v1/experience/2
{
  "name":"花园"
}

POST askdog_v1/experience/3
{
  "name":"第一次看电影"
}

GET askdog_v1/experience/_search
{
  "query": {
    "match": {
      "name": "huayuan"
    }
  },
  "highlight": {
    "pre_tags": [
      "`<ss>`"
    ],
    "post_tags": [
      "`</ss>`"
    ],
    "require_field_match": true,
    "fields": {
      "name": {
        "number_of_fragments": 1,
        "no_match_size": 20,
        "fragment_size": 20
      }
    }
  }
}

**results:**

{
  "took": 1,
  "timed_out": false,
  "_shards": {
    "total": 5,
    "successful": 5,
    "failed": 0
  },
  "hits": {
    "total": 3,
    "max_score": 0.6986275,
    "hits": [
      {
        "_index": "askdog_v1",
        "_type": "experience",
        "_id": "2",
        "_score": 0.6986275,
        "_source": {
          "name": "花园"
        },
        "highlight": {
          "name": [
            "`<ss>`花园`</ss>`"
          ]
        }
      },
      {
        "_index": "askdog_v1",
        "_type": "experience",
        "_id": "1",
        "_score": 0.5239706,
        "_source": {
          "name": "美丽的花园"
        },
        "highlight": {
          "name": [
            "`<ss>`美丽的花园`</ss>`"
          ]
        }
      },
      {
        "_index": "askdog_v1",
        "_type": "experience",
        "_id": "3",
        "_score": 0.13682276,
        "_source": {
          "name": "第一次看电影"
        },
        "highlight": {
          "name": [
            "`<ss>`第一次看电影`</ss>`"
          ]
        }
      }
    ]
  }
}

what shou i do next  
thanks a lot

**Comment by wanming** [comment]
都是中国人，何必要用英文呢

**Comment by nikolamakin** [comment]
zip 压缩包我下载好并且解压放到plugins 了，已启动就报错。我就问一下是不是需要mvn编译一下？

**Comment by UchihaYuki** [comment]
@medcl 
我是用的8.1.2, 用的docker，解压到/usr/share/elasticsearch/plugins的，启动时报错：
```
uncaught exception in thread [main]


java.lang.IllegalStateException: Could not load plugin descriptor for plugin directory [elasticsearch-analysis-pinyin-8.1.2]


Likely root cause: java.nio.file.NoSuchFileException: /usr/share/elasticsearch/plugins/elasticsearch-analysis-pinyin-8.1.2/plugin-descriptor.properties


	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)


	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)


	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)


	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:218)


	at java.base/java.nio.file.Files.newByteChannel(Files.java:380)


	at java.base/java.nio.file.Files.newByteChannel(Files.java:432)


	at java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:422)


	at java.base/java.nio.file.Files.newInputStream(Files.java:160)


	at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:156)


	at org.elasticsearch.plugins.PluginsService.readPluginBundle(PluginsService.java:418)


	at org.elasticsearch.plugins.PluginsService.findBundles(PluginsService.java:395)


	at org.elasticsearch.plugins.PluginsService.getPluginBundles(PluginsService.java:388)


	at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:153)


	at org.elasticsearch.node.Node.<init>(Node.java:386)


	at org.elasticsearch.node.Node.<init>(Node.java:284)


	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:234)


	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:234)


	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:358)


	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:166)


	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:157)


	at org.elasticsearch.common.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:81)


	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:112)


	at org.elasticsearch.cli.Command.main(Command.java:77)


	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:122)


	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:80)


For complete error details, refer to the log at /usr/share/elasticsearch/logs/docker-cluster.log
```

**Comment by UchihaYuki** [comment]
用官方的方法安装也报错：
```
elasticsearch@es:~/bin$ ./elasticsearch-plugin install https://github.com/medcl/elasticsearch-analysis-pinyin/archive/refs/tags/v8.1.2.zip
-> Installing https://github.com/medcl/elasticsearch-analysis-pinyin/archive/refs/tags/v8.1.2.zip
-> Downloading https://github.com/medcl/elasticsearch-analysis-pinyin/archive/refs/tags/v8.1.2.zip
-> Failed installing https://github.com/medcl/elasticsearch-analysis-pinyin/archive/refs/tags/v8.1.2.zip
-> Rolling back https://github.com/medcl/elasticsearch-analysis-pinyin/archive/refs/tags/v8.1.2.zip
-> Rolled back https://github.com/medcl/elasticsearch-analysis-pinyin/archive/refs/tags/v8.1.2.zip
Exception in thread "main" java.nio.file.NoSuchFileException: /usr/share/elasticsearch/plugins/.installing-15137081558245689471/plugin-descriptor.properties
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:218)
        at java.base/java.nio.file.Files.newByteChannel(Files.java:380)
        at java.base/java.nio.file.Files.newByteChannel(Files.java:432)
        at java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:422)
        at java.base/java.nio.file.Files.newInputStream(Files.java:160)
        at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:156)
        at org.elasticsearch.plugins.cli.InstallPluginAction.loadPluginInfo(InstallPluginAction.java:823)
        at org.elasticsearch.plugins.cli.InstallPluginAction.installPlugin(InstallPluginAction.java:883)
        at org.elasticsearch.plugins.cli.InstallPluginAction.execute(InstallPluginAction.java:244)
        at org.elasticsearch.plugins.cli.InstallPluginCommand.execute(InstallPluginCommand.java:88)
        at org.elasticsearch.common.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:81)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:112)
        at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:95)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:112)
        at org.elasticsearch.cli.Command.main(Command.java:77)
        at org.elasticsearch.plugins.cli.PluginCli.main(PluginCli.java:36)
```

**Comment by UchihaYuki** [comment]
失误失误，已解决：
```
/usr/share/elasticsearch/bin/elasticsearch-plugin install https://github.com/medcl/elasticsearch-analysis-pinyin/releases/download/v8.1.2/elasticsearch-analysis-pinyin-8.1.2.zip
```
