### ISSUE TITLE
pinyin分词+highlight(with_positions_offsets) 出错问题

### ISSUE THREAD

**Issue by jie123108** [medcl/elasticsearch-analysis-pinyin#86]
### 问题描述：
使用拼音后，对alias.py字段进行高亮，会出错。同样的信息，原生字段没有问题。
另外，该问题不是所有记录都有问题的。但是我的测试示例是一定会出错的。
我测试了很多种情况，也只有数组的字段会有问题。

不知道是analysis-pinyin的问题，还是elasticsearch的问题。

### 出错信息。
```
[2017-02-10T17:26:11,185][DEBUG][o.e.a.s.TransportSearchAction] [57jXSnL] [5725] Failed to execute fetch phase
org.elasticsearch.transport.RemoteTransportException: [57jXSnL][127.0.0.1:9300][indices:data/read/search[phase/fetch/id]]
Caused by: org.elasticsearch.search.fetch.FetchPhaseExecutionException: Fetch Failed [Failed to highlight field [alias.py]]
        at org.elasticsearch.search.fetch.subphase.highlight.FastVectorHighlighter.highlight(FastVectorHighlighter.java:199) ~[elasticsearch-5.1.1.jar:5.1.1]
        at org.elasticsearch.search.fetch.subphase.highlight.HighlightPhase.hitExecute(HighlightPhase.java:124) ~[elasticsearch-5.1.1.jar:5.1.1]
        at org.elasticsearch.search.fetch.FetchPhase.execute(FetchPhase.java:163) ~[elasticsearch-5.1.1.jar:5.1.1]
        at org.elasticsearch.search.SearchService.executeFetchPhase(SearchService.java:502) ~[elasticsearch-5.1.1.jar:5.1.1]
        at org.elasticsearch.action.search.SearchTransportService$13.messageReceived(SearchTransportService.java:356) ~[elasticsearch-5.1.1.jar:5.1.1]
        at org.elasticsearch.action.search.SearchTransportService$13.messageReceived(SearchTransportService.java:353) ~[elasticsearch-5.1.1.jar:5.1.1]
        at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:69) ~[elasticsearch-5.1.1.jar:5.1.1]
        at org.elasticsearch.transport.TransportService$6.doRun(TransportService.java:577) [elasticsearch-5.1.1.jar:5.1.1]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:527) [elasticsearch-5.1.1.jar:5.1.1]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-5.1.1.jar:5.1.1]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_111]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_111]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -4
        at java.lang.String.substring(String.java:1967) ~[?:1.8.0_111]
        at org.apache.lucene.search.vectorhighlight.BaseFragmentsBuilder.makeFragment(BaseFragmentsBuilder.java:180) ~[lucene-highlighter-6.3.0.jar:6.3.0 a66a44513ee8191e25b477372094bfa846450316 - shalin - 2016-11-02 19:47:55]
        at org.elasticsearch.search.fetch.subphase.highlight.SimpleFragmentsBuilder.makeFragment(SimpleFragmentsBuilder.java:43) ~[elasticsearch-5.1.1.jar:5.1.1]
        at org.apache.lucene.search.vectorhighlight.BaseFragmentsBuilder.createFragments(BaseFragmentsBuilder.java:144) ~[lucene-highlighter-6.3.0.jar:6.3.0 a66a44513ee8191e25b477372094bfa846450316 - shalin - 2016-11-02 19:47:55]
        at org.apache.lucene.search.vectorhighlight.FastVectorHighlighter.getBestFragments(FastVectorHighlighter.java:186) ~[lucene-highlighter-6.3.0.jar:6.3.0 a66a44513ee8191e25b477372094bfa846450316 - shalin - 2016-11-02 19:47:55]
        at org.elasticsearch.search.fetch.subphase.highlight.FastVectorHighlighter.highlight(FastVectorHighlighter.java:175) ~[elasticsearch-5.1.1.jar:5.1.1]
        at org.elasticsearch.search.fetch.subphase.highlight.HighlightPhase.hitExecute(HighlightPhase.java:124) ~[elasticsearch-5.1.1.jar:5.1.1]
        at org.elasticsearch.search.fetch.FetchPhase.execute(FetchPhase.java:163) ~[elasticsearch-5.1.1.jar:5.1.1]
        at org.elasticsearch.search.SearchService.executeFetchPhase(SearchService.java:502) ~[elasticsearch-5.1.1.jar:5.1.1]
        at org.elasticsearch.action.search.SearchTransportService$13.messageReceived(SearchTransportService.java:356) ~[elasticsearch-5.1.1.jar:5.1.1]
        at org.elasticsearch.action.search.SearchTransportService$13.messageReceived(SearchTransportService.java:353) ~[elasticsearch-5.1.1.jar:5.1.1]
        at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:69) ~[elasticsearch-5.1.1.jar:5.1.1]
        at org.elasticsearch.transport.TransportService$6.doRun(TransportService.java:577) ~[elasticsearch-5.1.1.jar:5.1.1]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:527) ~[elasticsearch-5.1.1.jar:5.1.1]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-5.1.1.jar:5.1.1]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[?:1.8.0_111]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[?:1.8.0_111]
        at java.lang.Thread.run(Thread.java:745) ~[?:1.8.0_111]
```

### 测试方法
```
curl -XDELETE http://localhost:9200/test
curl -XPUT http://localhost:9200/test/ -d'{}' 
curl -XPOST http://localhost:9200/test/test/_mapping -d'{
  "test": {
    "_all": {
      "search_analyzer": "ik_max_word", 
      "store": "False", 
      "analyzer": "ik_max_word", 
      "term_vector": "no"
    }, 
    "properties": {
      "alias": {
        "include_in_all": true, 
        "type": "text", 
        "search_analyzer": "ik_max_word", 
        "analyzer": "ik_max_word", 
        "fields": {
          "py": {
            "boost": 8, 
            "type": "text", 
            "analyzer": "pinyin", 
            "term_vector": "with_positions_offsets"
          }
        }, 
        "boost": 10
      }   
    }
  }
}'

curl -XDELETE http://127.0.0.1:9200/test/test/1
curl -XPOST http://127.0.0.1:9200/test/test/1 -d '{"alias" : [ "厕所：难言的历史","疯狂的厕所" ]}'
# search test
curl -X POST  'http://127.0.0.1:9200/test/test/_search' \
-d '{
"query":{"function_score":{"query":{"bool":{"must":[{"multi_match":{"fields":["alias.py"],
"query":"ceshi"}}]
}}
}},
"highlight":{"fields":{"alias.py":{}}}
}'
```

**Comment by medcl** [comment]
用的什么版本的插件呢？

**Comment by jie123108** [comment]
就是elasticsearch-rtf-5.1.1打包的版本。没有安装其它额外插件。

**Comment by medcl** [comment]
@jie123108 这个是一个已知的 bug，后面的版本已经 fix 了，如：5.2.0
rtf 还没更新

**Comment by jie123108** [comment]
@medcl  我升级成了5.2.0版本的(包括es及ik,pinyin插件)，问题依然存在。还是会报一样的错误。使用我上面的测试方法能复现问题。

**Comment by medcl** [comment]
@jie123108 好的，我看看，谢谢反馈

**Comment by medcl** [comment]
@jie123108 你可以对将 mapping 里面的  `"term_vector": "with_positions_offsets"` 改成          "term_vector": "with_offsets" 么？
应该就能解决高亮的问题

**Comment by jie123108** [comment]
@medcl 谢谢回复啊。
测试用例，使用这个配置是没问题了。过几天有空我把线上配置修改下，再线上测试看看。
