### ISSUE TITLE
exception thrown on elasticsearch 5.2.0

### ISSUE THREAD

**Issue by chicheongweng** [medcl/elasticsearch-analysis-pinyin#87]
(searchservice) ~/Downloads/elasticsearch-5.2.0 $ > ls plugins/
elasticsearch-analysis-pinyin-5.2.0.jar	nlp-lang-1.7.jar
elasticsearch-analysis-pinyin-5.2.0.zip	plugin-descriptor.properties

(searchservice) ~/Downloads/elasticsearch-5.2.0 $ > [2017-02-13T17:38:50,234][INFO ][o.e.n.Node               ] [] initializing ...
[2017-02-13T17:38:50,286][INFO ][o.e.e.NodeEnvironment    ] [hEi7J3L] using [1] data paths, mounts [[/ (/dev/disk1)]], net usable_space [496.7gb], net total_space [930.7gb], spins? [unknown], types [hfs]
[2017-02-13T17:38:50,286][INFO ][o.e.e.NodeEnvironment    ] [hEi7J3L] heap size [1.9gb], compressed ordinary object pointers [true]
[2017-02-13T17:38:50,304][INFO ][o.e.n.Node               ] node name [hEi7J3L] derived from node ID [hEi7J3LlRnickLe3F6NgxA]; set [node.name] to override
[2017-02-13T17:38:50,306][INFO ][o.e.n.Node               ] version[5.2.0], pid[17680], build[24e05b9/2017-01-24T19:52:35.800Z], OS[Mac OS X/10.12.1/x86_64], JVM[Oracle Corporation/Java HotSpot(TM) 64-Bit Server VM/1.8.0_45/25.45-b02]
[2017-02-13T17:38:50,842][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: java.lang.IllegalStateException: Could not load plugin descriptor for existing plugin [elasticsearch-analysis-pinyin-5.2.0.jar]. Was the plugin built before 2.0?
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:125) ~[elasticsearch-5.2.0.jar:5.2.0]
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:112) ~[elasticsearch-5.2.0.jar:5.2.0]
	at org.elasticsearch.cli.SettingCommand.execute(SettingCommand.java:54) ~[elasticsearch-5.2.0.jar:5.2.0]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122) ~[elasticsearch-5.2.0.jar:5.2.0]
	at org.elasticsearch.cli.Command.main(Command.java:88) ~[elasticsearch-5.2.0.jar:5.2.0]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:89) ~[elasticsearch-5.2.0.jar:5.2.0]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:82) ~[elasticsearch-5.2.0.jar:5.2.0]
Caused by: java.lang.IllegalStateException: Could not load plugin descriptor for existing plugin [elasticsearch-analysis-pinyin-5.2.0.jar]. Was the plugin built before 2.0?
	at org.elasticsearch.plugins.PluginsService.getPluginBundles(PluginsService.java:295) ~[elasticsearch-5.2.0.jar:5.2.0]
	at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:131) ~[elasticsearch-5.2.0.jar:5.2.0]
	at org.elasticsearch.node.Node.<init>(Node.java:297) ~[elasticsearch-5.2.0.jar:5.2.0]
	at org.elasticsearch.node.Node.<init>(Node.java:232) ~[elasticsearch-5.2.0.jar:5.2.0]
	at org.elasticsearch.bootstrap.Bootstrap$6.<init>(Bootstrap.java:241) ~[elasticsearch-5.2.0.jar:5.2.0]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:241) ~[elasticsearch-5.2.0.jar:5.2.0]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:333) ~[elasticsearch-5.2.0.jar:5.2.0]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:121) ~[elasticsearch-5.2.0.jar:5.2.0]
	... 6 more
Caused by: java.nio.file.FileSystemException: /Users/chicheongweng/Downloads/elasticsearch-5.2.0/plugins/elasticsearch-analysis-pinyin-5.2.0.jar/plugin-descriptor.properties: Not a directory
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:91) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107) ~[?:?]
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214) ~[?:?]
	at java.nio.file.Files.newByteChannel(Files.java:361) ~[?:1.8.0_45]
	at java.nio.file.Files.newByteChannel(Files.java:407) ~[?:1.8.0_45]
	at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384) ~[?:1.8.0_45]
	at java.nio.file.Files.newInputStream(Files.java:152) ~[?:1.8.0_45]
	at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:86) ~[elasticsearch-5.2.0.jar:5.2.0]
	at org.elasticsearch.plugins.PluginsService.getPluginBundles(PluginsService.java:292) ~[elasticsearch-5.2.0.jar:5.2.0]
	at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:131) ~[elasticsearch-5.2.0.jar:5.2.0]
	at org.elasticsearch.node.Node.<init>(Node.java:297) ~[elasticsearch-5.2.0.jar:5.2.0]
	at org.elasticsearch.node.Node.<init>(Node.java:232) ~[elasticsearch-5.2.0.jar:5.2.0]
	at org.elasticsearch.bootstrap.Bootstrap$6.<init>(Bootstrap.java:241) ~[elasticsearch-5.2.0.jar:5.2.0]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:241) ~[elasticsearch-5.2.0.jar:5.2.0]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:333) ~[elasticsearch-5.2.0.jar:5.2.0]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:121) ~[elasticsearch-5.2.0.jar:5.2.0]
	... 6 more

**Comment by medcl** [comment]
delete elasticsearch-analysis-pinyin-5.2.0.zip
